package com.trackwise.entity;

public enum NotificationType {
    BUDGET_ALERT,
    GOAL_MILESTONE,
    GOAL_COMPLETED,
    GOAL_ACHIEVED,
    GOAL_OVERDUE,
    OVERSPENDING_ALERT,
    MONTHLY_SUMMARY,
    WEEKLY_SUMMARY,
    SECURITY_ALERT,
    SYSTEM_NOTIFICATION,
    TRANSACTION_SUCCESS,
    CATEGORY_UPDATE
}
